baseurl = "/"
languageCode = "en-us"
title = "Left Eyes Of Darkness"
theme = "hugo-theme-casper"
disqusShortname = "mormolycia"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "blog"
  cover = "images/cover.jpg"
  author = "m"
  authorlocation = "Toronto,Ontario"
  authorwebsite = "http://leteyeofdarkness.com"
  bio= "Digital Artist"
  logo = "images/logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  twitterName = "mormolycia"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
    twitter = "mormolycia"
